### ISSUE TITLE
Disable SSL for local testing

### ISSUE THREAD

**Issue by juanluisbaptiste** [tiredofit/docker-wordpress#1]
Hi,

Could it be possible to disable SSL for local testing ? when I load the test site the first time it gets redirected to https. If I force http:// on the url then wordpress installer launches but css are broken, even after finishing the install wizard.

I'm testing your image in my laptop behind a private lan where I cannot generate a letsencrypt certificate. 

Thank you.

**Comment by tiredofit** [comment]
Sure, just give me about 20 minutes to build it into the image the ability to switch it off

**Comment by tiredofit** [comment]
Try using `ENABLE_HTTPS_REVERSE_PROXY=FALSE` in your docker-compose.yml and you should be able to access without a HTTPS terminator. Let me know if that works.

**Comment by juanluisbaptiste** [comment]
Wow this is fast, thanks !! I'll test right now and report back.

**Comment by juanluisbaptiste** [comment]
Did you push a new docker image ? I'm trying building it but currently is failing for me, not finding pdftk, but probably it is a mirror issue as I was able to to build it before I opened this issue.

**Comment by tiredofit** [comment]
My apologies, the wordpress build failed on Dockerhub, Resubmitting and also stripping pdftk - that shouldn't be in there and was meant for my private repo for a different need.

**Comment by tiredofit** [comment]
Should be bout 30 minutes for this to finish its building.

**Comment by juanluisbaptiste** [comment]
After setting ENABLE_HTTPS_REVERSE_PROXY=FALSE it stills redirects to https.

**Comment by tiredofit** [comment]
OK, let me do a deep dive here and see where its going wrong.

**Comment by tiredofit** [comment]
Sorry for the delay. I forgot to save one of the files before the last commit (!)

This new one is building and tested working on localhost.

PS - Thanks for your OTRS Image. It was one of the first images I ever found in 2016 when starting with Docker and learned based on how you built things.

**Comment by juanluisbaptiste** [comment]
> Sorry for the delay. I forgot to save one of the files before the last commit (!)
> 
> This new one is building and tested working on localhost.
> 

It is working, thanks !! now to get it working with a zabbix server.

> PS - Thanks for your OTRS Image. It was one of the first images I ever found in 2016 when starting with Docker and learned based on how you built things.

You are welcome, I'm glad to know that it was helpful to you, as you images are me now , you will be saving me a lot of time with your Zabbix integration, thanks for those too !! :metal:

**Comment by tiredofit** [comment]
Here's how I made it work in my environment:
![image](https://user-images.githubusercontent.com/23528985/69162564-b7547780-0aa1-11ea-8a60-404f9acc4e93.png)

Each baremetal host has a Zabbix Agent, and inside Docker there is a zabbix-proxy, with the reasoning that all containers on the host can talk to the proxy while letting it do the heavy lifting with communicating to the server. There are a few funky iptables rules I had to setup to make it work, if you need contact me privately and I'll share some config.

**Comment by juanluisbaptiste** [comment]
>  There are a few funky iptables rules I had to setup to make it work, if you need contact me privately and I'll share some config.

I will surely do, closing this issue, thanks again !
