### ISSUE TITLE
DB not updating when SITE_URL is changed

### ISSUE THREAD

**Issue by telepibe** [tiredofit/docker-wordpress#17]
Hi!
I was checking DB update functionality but it's not working. There's an error in:
https://github.com/tiredofit/docker-wordpress/blob/1d314065b748182719a755e8208a70d1ad4a47d0/install/etc/cont-init.d/30-wordpress#L72

OLD_URL should be OLDURL.

Thanks for all your work. Awesome docker images. I'm learning a lot.

**Comment by tiredofit** [comment]
Hi, thanks for the compliments! 
I've released a new version (`5.3.4` or `latest`) that uses the correct variables, so the SITE_URL should correctly function.
Thanks for identifying and submitting.

**Comment by telepibe** [comment]
Fixed in latest release.

Thanks!
