### ISSUE TITLE
Builds for different php versions

### ISSUE THREAD

**Issue by juanluisbaptiste** [tiredofit/docker-wordpress#2]
Hi,

Have you thought of pushing multiple images built against different php-fpm versions ? I'm currently migrating several wordpress sites to docker, but they support different php versions because of some plugins, ranging from 7.0 to 7.3. 

I don't know how difficult this could be to implement within your CI/CD pipeline, but having different php versions like the official images does could be of great help on situations like this one.

Cheers,

**Comment by tiredofit** [comment]
Yes, thats quite easy for me to do. In fact after rewriting the image in the past few days based on your interest in it I rolled ours over to production and found that some plugins were barking especially with PHP 7.3. With PHP 7.4 right around the corner it would be prudent for me to build 7.0, 7.1, 7.2 and 7.3. I could even do a 5.6 but that is way EOL. I'll have something ready for tomorrow.

Hope you like the new enhancements in the new image.

**Comment by juanluisbaptiste** [comment]
Excellent

> Yes, thats quite easy for me to do. In fact after rewriting the image in the past few days based on your interest in it I rolled ours over to production and found that some plugins were barking especially with PHP 7.3. With PHP 7.4 right around the corner it would be prudent for me to build 7.0, 7.1, 7.2 and 7.3. I could even do a 5.6 but that is way EOL. I'll have something ready for tomorrow.
> 

Excellent, perfect timing ;)

> Hope you like the new enhancements in the new image.

The autoinstall feature seems sweet and I will definitively have a use for that :)

**Comment by tiredofit** [comment]
OK! Here you go:
`docker pull tiredofit/wordpress:latest` (Will always follow latest PHP Version)
`docker pull tiredofit/wordpress:php7.3` (PHP 7.3)
`docker pull tiredofit/wordpress:php7.2` (PHP 7.2)
`docker pull tiredofit/wordpress:php7.1` (PHP 7.1)
`docker pull tiredofit/wordpress:php7.0` (PHP 7.0)
`docker pull tiredofit/wordpress:php5.6` (PHP 5.6)

Also there are version tags that relate to the changelogs as well. Check the Tags/Builds section on Docker Hub to see how they work. This was rather simple - I've split the branches and just altered one line in each Dockerfile to utilize a different variant of my `tiredofit/nginx-php-fpm` image.

Hope this works for you.

**Comment by juanluisbaptiste** [comment]
Thanks, I will check them out later.

**Comment by juanluisbaptiste** [comment]
They work fine, thanks.

PS Did you see an email I sent you to the email address in your Dockerfiles ?

**Comment by tiredofit** [comment]
I did! I wrote a very lengthy reply as well.
Try looking in Spam / Junk? Wonder if my mail server is being rejected.

**Comment by juanluisbaptiste** [comment]
Got it, lengithly indeed, I'll check it out over the week and answer you.

I'll close this now.

Thanks again.
